In [12]:
a = 3

In [14]:
print(a)

3


In [20]:
# team problem 
import random 

def team(n):
    attemted_problems = 0
    
    n_probs = [[random.randint(0,1) for x in range(3)] for y in range(n)]
    print(n_probs)
    
    for i in n_probs:
        c = 0
        for k in i:
            if k == 1:
                c += 1
            else:
                continue
                
        if c >= 2:
            attemted_problems += 1
            
        else:
            continue
    
    return attemted_problems
        
    
team(4)

[[0, 0, 1], [0, 1, 1], [0, 0, 0], [1, 0, 0]]


1

In [21]:
import random

def team2(n_probs):
    
    attempted_probs = 0
    problems = [[random.randint(0,1) for x in range(3)] for y in range(n_probs)]
    print(problems)
    
    if 1 <= n_probs <= 1000:
    
        for i in problems:
            c = 0
            for j in range(len(i)): 
                if i[j] == 1:
                    c += 1

                else:
                    continue

            if c >= 2:
                attempted_probs += 1

            else:
                continue

        return attempted_probs
    
    else:
        return f'Array size is too large: {n_probs}'


team2(2)

[[0, 1, 0], [0, 0, 0]]


0

In [22]:
def k_contestents(total_contestents):
    

#     finisher_score = random.randint(0,10)
#     scores = sorted([random.randint(0,10) for x in range(total_contestents)], reverse=True)

    scores = [0,0,0,0]
    finisher_score = 2
    
    print(f'scores: {scores}')
    print(f'finisher score: {finisher_score}')
    
    if finisher_score in scores:
        return finisher_score + 1
    
    else:
        return f'Finisher not in scores {finisher_score}'

k_contestents(10)

scores: [0, 0, 0, 0]
finisher score: 2


'Finisher not in scores 2'

In [38]:
def dominos(rows, cols):
    
    return (rows * cols) // 2
import math 

if __name__ == '__main__':
    print(dominos(3, 2))

3


In [42]:
def bit_pp():
    
    n = int(input())
    result = 0
    statements = []
    
    for i in range(n):
        statement = str(input())
        statements.append(statement)
        
    for j in range(len(statements)):
        if '++' in statements[j]:
            result += 1
        else:
            result -= 1
            
    return result

if __name__ == '__main__':
    print(bit_pp())

2
x++
--x
0


In [10]:
def lexicographic_string():
    
    string1 = str(input()).lower()
    string2 = str(input()).lower()
    
    if len(string1) == len(string2):

        lexo_dict = {}
        count = 0
        alphabets = 'abcdefghijklmnopqrstuvwxyz'.lower()

        while count < len(alphabets):
            lexo_dict[alphabets[count]] = count
            count += 1
            
        strings_list = list(zip(string1, string2))
        
        for val in strings_list:
            if lexo_dict[val[0]] > lexo_dict[val[1]]:
                return 1
            elif lexo_dict[val[1]] > lexo_dict[val[0]]:
                return -1
            
            else:
                continue
                
        return 0
        
    else:
        return 'string lengths are not same!'

if __name__ == '__main__':
    print(lexicographic_string())

aslkjlkasdd
asdlkjdajwi
1


In [5]:
def lexicographs():
    s1 = str(input())
    s2 = str(input())
    
    for i, j in zip(s1, s2):
        if i == j:
            
        
        
lexicographs()
                

aaaa
aaaZ
a a
a a
a a
a Z


In [7]:
import random 
import numpy as np

def beautiful_matrix(row_size, col_size):
    
    ROW_SIZE, COL_SIZE = (row_size, col_size)
    
    zeros = np.zeros((ROW_SIZE, COL_SIZE))
    
    A = random.randint(0, len(zeros)-1)
    B = random.randint(0, len(zeros[0])-1)
    iterations = 0
    zeros[A][B] = 1
    
    matrix_centre = ROW_SIZE // 2
    
    print(zeros)
    
    for r in range(len(zeros)):
        for c in range(len(zeros[0])):
            if zeros[r][c] == 1:
                row_no, col_no = (r, c)
                print(f'Initial position: {row_no, col_no}')
                
                if row_no == matrix_centre and col_no == matrix_centre:
                    return 0 
                else:
                    if row_no > matrix_centre:
                        while row_no != matrix_centre:
                            row_no -= 1
                            iterations += 1
                            
                    elif row_no < matrix_centre:
                        while row_no != matrix_centre:
                            row_no += 1
                            iterations += 1
                            
                    if col_no > matrix_centre:
                        while col_no != matrix_centre:
                            col_no -= 1
                            iterations += 1
                            
                    elif col_no < matrix_centre:
                        while col_no != matrix_centre:
                            col_no += 1
                            iterations += 1
                            
                    else:
                        None
                    
            else:
                continue 
    
    print(f'final rows and cols: {row_no, col_no}')
                
    return f'minimum iterations needed: {iterations}'
    
print(beautiful_matrix(5, 5))

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Initial position: (0, 4)
final rows and cols: (2, 2)
minimum iterations needed: 4


In [19]:
def test(n):
    if n > 1:
        print('n: %s' %n)
        # find the recurrence relations of all the numbers 
        # in adjacecy matrix!
        test(n-1)
        
    else:
        return n
    
test(5)

n: 5
n: 4
n: 3
n: 2


In [37]:
summans = str(input())

if len(summans) == 0 or ' ' in summans or len(summans) > 100:
    print(f'string not valid: {summans}')

xenia_list = sorted([int(x) for x in summans.split('+')])

for idx, num in enumerate(xenia_list):
    if num >= 4:
        xenia_list.pop(idx)
    else:
        continue

print('+'.join([str(x) for x in xenia_list]))

1+2+3+4
1+2+3


In [50]:
word = str(input())

if (len(word) > 10000) or (word == ''):
    print(f'string length too big: {len(word)}')
    
first_letter = word[0].upper()

print(str(first_letter) + str(word[1:]))

applE
A
ApplE


In [16]:
stones = int(input())
colors = str(input()).upper()
colors_list = ['R', 'G', 'B']

for c in colors:
    if c not in colors_list:
        print(f'wrong color inserted: {c}')
    else:
        continue

if stones > 50:
    print(f'too much stones on the table: {stones}')

if len(colors) != stones:
    print(f'fix the length for colors: {len(colors)}')

print(f'stones: colors: {stones, colors}')

count = 0
for i in range(len(colors) -1):
    if colors[i] == colors[i+1]:
        count += 1
    else:
        continue
        
print(f'minimum stones: {count}')

4
brgb
stones: colors: (4, 'BRGB')
minimum stones: 0


In [20]:
string = str(input('Enter name: '))

if string.lower() == '' or len(string.lower()) > 100:
    print(f'name not acceptable: {string}')
else:
    string_chars = {}

    for char in string:
        if char in string_chars:
            string_chars[char] += 1
        else:
            string_chars[char] = 1

    print(f'distinct chars: {len(string_chars.keys())}')

    if len(string_chars.keys()) % 2 != 0:
        print('IGNORE HIM!')
    else:
        print('CHAR WITH HER')

Enter name: adj;f
distinct chars: 5
IGNORE HIM!


In [8]:
# soldiers and bananas 
import numpy as np 

k, n, w = int(input()), int(input()), int(input())

if 1 <= k and w <= 1000 and 0 <= n <= 10**9:

    total_banana_amount = 0

    for c in range(1,w+1):
        total_banana_amount += k * c

    print(f'total amount: {total_banana_amount}')

    borrow_amount = total_banana_amount - n

    print(f'borrow amount: {borrow_amount}')
    
else:
    print('wrong values provided')

0
17
4
wrong values provided


In [71]:
# limx and bob
def limx_and_bob():
    a, b = (int(x) for x in input().split())

    if a > 10 or b > 10:
        print(f'wrong weights: {a, b}')

    else:
        years = 1
        for _ in range(1, 100):
            limax_weight = a * 3
            bob_weight = b * 2

            if limax_weight > bob_weight:
                print(f'years needed: {years}')
                break

            else:
                years += 1
                a = limax_weight
                b = bob_weight

if __name__ == '__main__':
    limx_and_bob()

4 7
years needed: 2


In [28]:
string = str(input('Enter name: ')).lower()
new_string = []

if string == '' or len(string) > 100:
    print('wrong string')
else:

    for char in string:
        if char in new_string:
            continue 
        else:
            new_string.append(char)

    print(f'new string: {new_string}')

    if len(new_string) % 2==0:
        print('CHAT WITH HER!')
    else:
        print('IGNORE HIM!')

Enter name: umair/
new string: ['u', 'm', 'a', 'i', 'r', '/']
CHAT WITH HER!


In [6]:
s = 'umair'
s1 = dict.fromkeys(s)

print(s1)

{'u': None, 'm': None, 'a': None, 'i': None, 'r': None}


In [7]:
print(len(char_count))

5


In [8]:
print(char_count)

{'u': 5, 'm': 1, 'a': 1, 'i': 1, 'r': 1}


In [10]:
print(len(char_count))

5


In [5]:
def main():
    s = str(input())
    if (len(s) > 100) or (s == ''):
        print('wrong string: %s' %string)
        
    else:
        new_string = []
        
        for char in s:
            if char in new_string:
                continue 
            else:
                new_string.append(char)
                
        if len(new_string) % 2 == 0:
            print('CHAT WITH HER!')
        else:
            print('IGNORE HIM!')
        
if __name__ == '__main__':
    main()

umair
IGNORE HIM!


In [20]:
# soldiers and bananas 
import numpy as np 

# k -> cost of first banana
# w -> initial number of dollars soldier have
# n -> number of bananas soldier wants to buy 

def soldier_banana():
    k, w, n = int(input()), int(input()), int(input())

#     if (1 <= k) and (w <= 1000) and (0 <= n <= 10**9):
    total_amount = 0
    for c in range(1, w+1):
        total_amount += k * c
    print('total amount: %s' %total_amount)

    borrow_amount = total_amount - n

    if w > total_amount:
        print(0)
    else:
        print(f"borrow amount: {borrow_amount}")
        
#     else:
#         print('wong values provided!')
        
if __name__ == '__main__':
    soldier_banana()

3
17
4
total amount: 459
borrow amount: 455


In [67]:
def soldier_banana():
    k, n, w = map(int,input().split()) # k, n ,w = (int(x) for x in input().split())

    total_amt = 0

    for c in range(1, w+1):
        total_amt += c * k

    borrow_amt = total_amt - n

    if n >= total_amt:
        borrow_amt = 0
        print(borrow_amt)

    else:
        print(total_amt - n)
        
if __name__ == '__main__':
    soldier_banana()

3 17 4
13


In [17]:
def long_words():
    n = int(input())
    new_words = []
    for _ in range(n):
        word = str(input()).lower()
        
        if len(word) > 10:
            word_ = str(word[0]) + str(len(word[1:-1])) + str(word[-1])
            new_words.append(word_)
        else:
            new_words.append(word)
                             
    for i in range(len(new_words)):
        print(new_words[i])
if __name__ == '__main__':
    long_words()

4
word
word2
word3
localization
word
word2
word3
l10n


In [44]:
class Stack:
    def __init__(self):
        self.items = []
        
    def push(self, item):
        self.items.append(item)
        
    def pop(self, idx):
        self.items.pop(idx)
        
    def is_empty():
        return len(self.items) == 0
    
    def size(self):
        return len(self.items)
    
    def peek(self):
        return self.items[len(self.items) - 1]
    
    def __repr__(self):
        return f"Stack class"

In [45]:
s = Stack()

In [46]:
s.size()

0

In [47]:
s.push(1)

In [48]:
print(s)

Stack class


In [6]:
def k_substractions():
    
    n, k = (int(x) for x in input().split())
    
    for i in range(k):
        if n > 0:
            if n % 10 == 0:
                n /= 10
            else:
                n -= 1
                
        else:
            return n
        
    return int(n)

if __name__ == '__main__':
    print(k_substractions())

1000000000 9
1


In [3]:
def tram():
    stops = int(input())
    
    total = []
    exist, enter = [int(x) for x in input().split()]
    
    total.append((exist + enter))
    
    i = total[0]
    
    for stop in range(stops-1):
        exit, enter = [int(x) for x in input().split()]
        i = i - exit + enter
        total.append(i)
        
    return max(total)
        
if __name__ == '__main__':
    print(tram())

4
0 5
2 3
1 2
3 0
7


In [5]:
def elephant_visit():
    friend_house = int(input())
    
    if friend_house <= 5:
        return 1 
    elif friend_house % 5 == 0:
        return friend_house // 5
    else:
        return friend_house // 5 + 1
    
if __name__ == '__main__':
    print(elephant_visit())

1000000
200000


In [3]:
from collections import defaultdict

def word():
    word_ = str(input())
    
    char_dict = {'uppers': 0,
                'lowers': 0}
    
    for char in word_:
        if char.isupper() == True:
            char_dict['uppers'] += 1
        else:
            char_dict['lowers'] += 1
            
    if char_dict['uppers'] > char_dict['lowers']:
        return word_.upper()
    
    elif char_dict['uppers'] < char_dict['lowers']:
        return word_.lower()
    
    else:
        return word_.lower()

if __name__ == '__main__':
    print(word())

maTRIx
matrix


In [1]:
def queue():
    n, t = [int(x) for x in input().split()]
    string = str(input()).upper()
    
    idx = 0
    
    while idx <= t:
        for i in range(len(string) -1):
            if string[i] == 'B' and string[i+1] == 'G':
                string[i+1], string[i] = string[i], string[i+1]
            else:
                continue
                
        idx += 1
        
    return string

if __name__ == '__main__':
    print(queue())

5 1
BBGBG


TypeError: 'str' object does not support item assignment

In [19]:
def queue():
    n, t = [int(x) for x in input().split()]
    string = str(input()).upper()
    
    string = [str(x) for x in string]
    
    for i in range(t):
        for j in range(len(string) -1):
            if string[j] == 'B' and string[j+1] == 'G':
                string[i+1], string[i] = string[i], string[i+1]
                
            else:
                continue
            
    return ''.join(string)

if __name__ == '__main__':
    print(queue())

5 1
BGGBG
GBGBG


In [18]:
n, t = [int(x) for x in input().split()]
l = str(input()).upper()

l = [str(x) for x in l]

print(l)

idx = 0

while idx < t:
    
    for i in range(len(l) -1):
        if l[i] == 'B' and l[i+1] == 'G':
            l[i+1], l[i]= l[i], l[i+1]
        else:
            continue
            
    idx += 1
        
print(l)

5 1
BGGBG
['B', 'G', 'G', 'B', 'G']
['G', 'G', 'B', 'G', 'B']


In [16]:
t = 1
string = 'GGGB'

string = [str(x) for x in string] # ['B','G','G','B','G']

print(f"initial string: {string}")

count = 0
i = 0
indexes = []
while i < len(string):
    if string[i] == 'B' and string[i+1] == 'G':
        count += 1
        indexes.append(i)
        i += 1
    else:
        i += 1

new_string = []
for idx in indexes:
    string[idx+1], string[idx] = string[idx], string[idx+1]
new_string.append(string)
    
print(new_string)

initial string: ['G', 'G', 'G', 'B']


IndexError: list index out of range

In [23]:
n, t = [int(x) for x in input().split()]
string = str(input())

string = [str(x) for x in string]

def find_indexes(s):
    """find indexes to swap"""
    indexes = []
    for i in range(len(s)-1):
        if s[i] == 'B' and s[i+1] == 'G':
            indexes.append(i)
            
        else:
            continue
            
    return indexes

def swap_indexes(s_, t):
    i = 0
    while i < t:
        indexes = find_indexes(s_)
        for k in indexes:
            s_[k+1], s_[k] = s_[k], s_[k+1]
            
        i += 1
            
    return ''.join(s_)


if __name__ == '__main__':
    print(swap_indexes(string, time))

5 2
BGGBG
GGBGB
